[2025-04-28T16:13:05.615+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T16:13:05.873+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:59+00:00 [queued]>
[2025-04-28T16:13:05.886+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:59+00:00 [queued]>
[2025-04-28T16:13:05.888+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-04-28T16:13:05.911+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 15:30:59+00:00
[2025-04-28T16:13:05.919+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'scheduled__2025-04-28T15:30:59+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmppna_o226']
[2025-04-28T16:13:05.921+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=174) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T16:13:05.922+0000] {standard_task_runner.py:91} INFO - Job 65: Subtask insert_***
[2025-04-28T16:13:05.922+0000] {standard_task_runner.py:63} INFO - Started process 180 to run task
[2025-04-28T16:13:06.787+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres scheduled__2025-04-28T15:30:59+00:00 [running]> on host c6abaffabc50
[2025-04-28T16:13:08.459+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T15:30:59+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-04-28T15:30:59+00:00'
[2025-04-28T16:13:08.460+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T16:13:08.475+0000] {logging_mixin.py:188} INFO - Fetched Product Data: N
[2025-04-28T16:13:08.744+0000] {logging_mixin.py:188} INFO - Database connection established.
[2025-04-28T16:13:08.746+0000] {logging_mixin.py:188} INFO - Table creation or existence check passed.
[2025-04-28T16:13:08.746+0000] {logging_mixin.py:188} INFO - Error inserting data into PostgreSQL: string indices must be integers, not 'str'
[2025-04-28T16:13:08.747+0000] {logging_mixin.py:188} INFO - Connection closed.
[2025-04-28T16:13:08.747+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T16:13:08.748+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 75, in write_to_postgres
    raise e
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 60, in write_to_postgres
    product['name'],
    ~~~~~~~^^^^^^^^
TypeError: string indices must be integers, not 'str'
[2025-04-28T16:13:09.028+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=insert_***, run_id=scheduled__2025-04-28T15:30:59+00:00, execution_date=20250428T153059, start_date=20250428T161305, end_date=20250428T161309
[2025-04-28T16:13:09.045+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 65 for task insert_*** (string indices must be integers, not 'str'; 180)
[2025-04-28T16:13:09.068+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-28T16:13:09.398+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T16:13:09.401+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
