[2025-05-22T05:09:37.893+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-22T05:09:38.141+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.log_ingestion_audit manual__2025-05-22T05:08:25.032154+00:00 [queued]>
[2025-05-22T05:09:38.153+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.log_ingestion_audit manual__2025-05-22T05:08:25.032154+00:00 [queued]>
[2025-05-22T05:09:38.154+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-22T05:09:38.168+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgresOperator): log_ingestion_audit> on 2025-05-22 05:08:25.032154+00:00
[2025-05-22T05:09:38.174+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=280) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-22T05:09:38.174+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'log_ingestion_audit', 'manual__2025-05-22T05:08:25.032154+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpx0863246']
[2025-05-22T05:09:38.176+0000] {standard_task_runner.py:63} INFO - Started process 281 to run task
[2025-05-22T05:09:38.176+0000] {standard_task_runner.py:91} INFO - Job 377: Subtask log_ingestion_audit
[2025-05-22T05:09:38.819+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.log_ingestion_audit manual__2025-05-22T05:08:25.032154+00:00 [running]> on host 7af769768e51
[2025-05-22T05:09:44.296+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='papala.ramesh@quation.in,smilesoframs@gmail.com,ramesh.rams333@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='log_ingestion_audit' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T05:08:25.032154+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T05:08:25.032154+00:00'
[2025-05-22T05:09:44.298+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-22T05:09:44.315+0000] {sql.py:276} INFO - Executing: -- Insert audit log
INSERT INTO ingestion_audit (
    ingestion_date,
    source,
    record_count,
    status,
    notes,
    retry_count,
    start_time,
    end_time
)
VALUES (
    '2025-05-22',
    'random_product_api',
    0,
    'unknown',
    'no notes',
    0,
    ''::timestamp,
    ''::timestamp
);
[2025-05-22T05:09:44.317+0000] {crypto.py:82} WARNING - empty cryptography key - values will not be stored encrypted.
[2025-05-22T05:09:44.317+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-22T05:09:44.321+0000] {base.py:84} INFO - Using connection ID '***_default' for task execution.
[2025-05-22T05:09:44.530+0000] {sql.py:487} INFO - Running statement: -- Insert audit log
INSERT INTO ingestion_audit (
    ingestion_date,
    source,
    record_count,
    status,
    notes,
    retry_count,
    start_time,
    end_time
)
VALUES (
    '2025-05-22',
    'random_product_api',
    0,
    'unknown',
    'no notes',
    0,
    ''::timestamp,
    ''::timestamp
);, parameters: None
[2025-05-22T05:09:44.532+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-22T05:09:44.533+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 282, in execute
    output = hook.run(
             ^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 435, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/hooks/sql.py", line 492, in _run_command
    cur.execute(sql_statement)
psycopg2.errors.InvalidDatetimeFormat: invalid input syntax for type timestamp: ""
LINE 19:     ''::timestamp,
             ^

[2025-05-22T05:09:44.720+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=log_ingestion_audit, run_id=manual__2025-05-22T05:08:25.032154+00:00, execution_date=20250522T050825, start_date=20250522T050938, end_date=20250522T050944
[2025-05-22T05:09:44.743+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-22T05:09:44.743+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-05-22T05:09:45.976+0000] {email.py:282} INFO - Sent an alert email to ['papala.ramesh@quation.in', 'smilesoframs@gmail.com', 'ramesh.rams333@gmail.com']
[2025-05-22T05:09:48.441+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 377 for task log_ingestion_audit (invalid input syntax for type timestamp: ""
LINE 19:     ''::timestamp,
             ^
; 281)
[2025-05-22T05:09:48.468+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-22T05:09:48.677+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T05:09:48.679+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
