[2025-04-28T16:24:46.276+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T16:24:46.506+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [queued]>
[2025-04-28T16:24:46.521+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [queued]>
[2025-04-28T16:24:46.523+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 3
[2025-04-28T16:24:46.539+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 16:18:52.750094+00:00
[2025-04-28T16:24:46.545+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-04-28T16:18:52.750094+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpbc66_8xo']
[2025-04-28T16:24:46.547+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=185) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T16:24:46.548+0000] {standard_task_runner.py:91} INFO - Job 100: Subtask insert_***
[2025-04-28T16:24:46.548+0000] {standard_task_runner.py:63} INFO - Started process 186 to run task
[2025-04-28T16:24:47.338+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [running]> on host 0d0bf7d6bdbb
[2025-04-28T16:24:48.624+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T16:18:52.750094+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T16:18:52.750094+00:00'
[2025-04-28T16:24:48.625+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T16:24:48.647+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T16:24:48.648+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 15, in write_to_postgres
    data = json.loads(data)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-04-28T16:24:48.847+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-04-28T16:18:52.750094+00:00, execution_date=20250428T161852, start_date=20250428T162446, end_date=20250428T162448
[2025-04-28T16:24:48.866+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 100 for task insert_*** (Expecting value: line 1 column 1 (char 0); 186)
[2025-04-28T16:24:48.890+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-28T16:24:49.166+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T16:24:49.171+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
