[2025-04-28T16:19:00.219+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-04-28T16:19:00.510+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [queued]>
[2025-04-28T16:19:00.524+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [queued]>
[2025-04-28T16:19:00.526+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-04-28T16:19:00.560+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-04-28 16:18:52.750094+00:00
[2025-04-28T16:19:00.567+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-04-28T16:18:52.750094+00:00', '--job-id', '92', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmp4oyl62jo']
[2025-04-28T16:19:00.569+0000] {standard_task_runner.py:91} INFO - Job 92: Subtask insert_***
[2025-04-28T16:19:00.569+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=208) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-28T16:19:00.570+0000] {standard_task_runner.py:63} INFO - Started process 209 to run task
[2025-04-28T16:19:01.307+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-04-28T16:18:52.750094+00:00 [running]> on host 03e87209dbec
[2025-04-28T16:19:02.694+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-04-28T16:18:52.750094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-28T16:18:52.750094+00:00'
[2025-04-28T16:19:02.696+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-04-28T16:19:02.712+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-04-28T16:19:02.713+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 14, in write_to_postgres
    products = response_data.get('data', [])
               ^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
[2025-04-28T16:19:02.934+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-04-28T16:18:52.750094+00:00, execution_date=20250428T161852, start_date=20250428T161900, end_date=20250428T161902
[2025-04-28T16:19:02.950+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 92 for task insert_*** ('str' object has no attribute 'get'; 209)
[2025-04-28T16:19:02.995+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-04-28T16:19:03.261+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-04-28T16:19:03.264+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
