[2025-05-20T05:03:35.956+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-20T05:03:36.207+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-05-20T05:03:29.549243+00:00 [queued]>
[2025-05-20T05:03:36.222+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.insert_postgres manual__2025-05-20T05:03:29.549243+00:00 [queued]>
[2025-05-20T05:03:36.223+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-05-20T05:03:36.246+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): insert_postgres> on 2025-05-20 05:03:29.549243+00:00
[2025-05-20T05:03:36.256+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'insert_***', 'manual__2025-05-20T05:03:29.549243+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmpcc7pke22']
[2025-05-20T05:03:36.259+0000] {standard_task_runner.py:91} INFO - Job 333: Subtask insert_***
[2025-05-20T05:03:36.259+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=461) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-20T05:03:36.260+0000] {standard_task_runner.py:63} INFO - Started process 462 to run task
[2025-05-20T05:03:36.912+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.insert_postgres manual__2025-05-20T05:03:29.549243+00:00 [running]> on host bafcef54437d
[2025-05-20T05:03:37.995+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='papala.ramesh@quation.in,smilesoframs@gmail.com,ramesh.rams333@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='insert_***' AIRFLOW_CTX_EXECUTION_DATE='2025-05-20T05:03:29.549243+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-20T05:03:29.549243+00:00'
[2025-05-20T05:03:37.996+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-20T05:03:39.560+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-20T05:03:39.561+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/storage/postgres_loader/write_to_postgres.py", line 99, in write_to_postgres
    raise Exception(error_message)
Exception: column "names" of relation "products" does not exist
LINE 2:                 names, descriptions, ean, upc, image, net_pr...
                        ^

[2025-05-20T05:03:39.751+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=random_user_pipeline, task_id=insert_***, run_id=manual__2025-05-20T05:03:29.549243+00:00, execution_date=20250520T050329, start_date=20250520T050336, end_date=20250520T050339
[2025-05-20T05:03:39.767+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 333 for task insert_*** (column "names" of relation "products" does not exist
LINE 2:                 names, descriptions, ean, upc, image, net_pr...
                        ^
; 462)
[2025-05-20T05:03:39.811+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-20T05:03:40.047+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-05-20T05:03:40.063+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-20T05:03:40.067+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
