[2025-05-22T05:09:40.231+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-22T05:09:40.534+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: random_user_pipeline.branch_on_count manual__2025-05-22T05:08:25.032154+00:00 [queued]>
[2025-05-22T05:09:40.547+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: random_user_pipeline.branch_on_count manual__2025-05-22T05:08:25.032154+00:00 [queued]>
[2025-05-22T05:09:40.548+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2025-05-22T05:09:40.563+0000] {taskinstance.py:2330} INFO - Executing <Task(BranchPythonOperator): branch_on_count> on 2025-05-22 05:08:25.032154+00:00
[2025-05-22T05:09:40.572+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=282) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-22T05:09:40.571+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'random_user_pipeline', 'branch_on_count', 'manual__2025-05-22T05:08:25.032154+00:00', '--job-id', '378', '--raw', '--subdir', 'DAGS_FOLDER/random_user_pipeline.py', '--cfg-path', '/tmp/tmp46n2rqad']
[2025-05-22T05:09:40.573+0000] {standard_task_runner.py:63} INFO - Started process 283 to run task
[2025-05-22T05:09:40.573+0000] {standard_task_runner.py:91} INFO - Job 378: Subtask branch_on_count
[2025-05-22T05:09:41.930+0000] {task_command.py:426} INFO - Running <TaskInstance: random_user_pipeline.branch_on_count manual__2025-05-22T05:08:25.032154+00:00 [running]> on host 7af769768e51
[2025-05-22T05:09:43.151+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='papala.ramesh@quation.in,smilesoframs@gmail.com,ramesh.rams333@gmail.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='random_user_pipeline' AIRFLOW_CTX_TASK_ID='branch_on_count' AIRFLOW_CTX_EXECUTION_DATE='2025-05-22T05:08:25.032154+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-22T05:08:25.032154+00:00'
[2025-05-22T05:09:43.153+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-22T05:09:43.166+0000] {baseoperator.py:400} WARNING - BranchPythonOperator.execute cannot be called outside TaskInstance!
[2025-05-22T05:09:43.166+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-22T05:09:43.167+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 269, in execute
    return self.do_branch(context, super().execute(context))
                                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/utils/branch_decision.py", line 7, in evaluate_data_count
    with open(sql, 'r') as f:
         ^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'sql/check_record_count_sensor.sql'
[2025-05-22T05:09:43.427+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=random_user_pipeline, task_id=branch_on_count, run_id=manual__2025-05-22T05:08:25.032154+00:00, execution_date=20250522T050825, start_date=20250522T050940, end_date=20250522T050943
[2025-05-22T05:09:43.449+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/utils/email.py:154 RemovedInAirflow3Warning: Fetching SMTP credentials from configuration variables will be deprecated in a future release. Please set credentials using a connection instead.
[2025-05-22T05:09:43.450+0000] {email.py:271} INFO - Email alerting: attempt 1
[2025-05-22T05:09:44.760+0000] {email.py:282} INFO - Sent an alert email to ['papala.ramesh@quation.in', 'smilesoframs@gmail.com', 'ramesh.rams333@gmail.com']
[2025-05-22T05:09:47.042+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 378 for task branch_on_count ([Errno 2] No such file or directory: 'sql/check_record_count_sensor.sql'; 283)
[2025-05-22T05:09:47.052+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-22T05:09:47.263+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py:1297 AirflowProviderDeprecationWarning: Call to deprecated class PostgresOperator. (Please use `airflow.providers.common.sql.operators.sql.SQLExecuteQueryOperator`.Also, you can provide `hook_params={'schema': <database>}`.)
[2025-05-22T05:09:47.284+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-22T05:09:47.291+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
